### ISSUE TITLE
Error with computeSumFactors

### ISSUE THREAD

**Issue by biobenkj** [MarioniLab/scran#1]
When QC'ing my 10X genomics scRNA-seq data, I've followed the tutorial as found here: https://f1000researchdata.s3.amazonaws.com/manuscripts/10712/3370b003-e980-4395-b641-daad385c65d3_9501_-__aaron_lun_v2.pdf?doi=10.12688/f1000research.9501.2

Everything proceeds normally until the normalization step and then receive the following error

```
Error in .local(x, ...) : unknown SEXP type for SCESet object
```

I'm currently using R v3.4.1 and have downloaded/installed everything from stable releases of scater and scran. Is this an issue of the C++ underneath returning something that the R v3.4.2 stable release version of SingleCellExperiment or scater (I'm creating a newSCESet with the count matrix)?

Thanks for your time!

**Comment by LTLA** [comment]
The `SCESet` object has been deprecated in favour of `SingleCellExperiment` in _scater_ and _scran_. To reflect this, an updated version of the workflow is available on the Bioconductor help pages, see:

https://www.bioconductor.org/help/workflows/simpleSingleCell/

... running on R 3.4.2 with Bioconductor 3.6. I'll get around to updating the F1000 version... eventually.

**Comment by biobenkj** [comment]
This definitely fixed it. Thanks!
