### ISSUE TITLE
Error in denoisePCA function

### ISSUE THREAD

**Issue by luolingqi** [MarioniLab/scran#15]
An error occurs while running denoisePCA function. 

Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4

Did anybody have the similar issue before?

**Comment by LTLA** [comment]
Never seen that before. From the call, it looks like an _irlba_ issue, but I don't understand why `nv=5`, as that's never set in any _scran_ function. Please provide the surrounding code for context; a minimum working example would be preferable.

**Comment by luolingqi** [comment]
Thanks for the quick response. Yes, it is an irlba issue. I checked the relevant posts, but failed to reach a solution.

Here the follwing is the command I used:
sce <- denoisePCA(sce, technical=new.trend, approx=TRUE)

It is pretty much what is in the Bioconductor workflow (**Analyzing single-cell RNA sequencing data from droplet-based protocols**).

Nice catch on the 'nv' value. I was debugging in R and the 'nv' is actually not 5, but 100 (as shown screenshot attached), even though the error message show 5. I assume that is only the default value shown in the function definition.

![image](https://user-images.githubusercontent.com/5617217/42961329-81e7fccc-8b5c-11e8-938d-2241eff2f105.png)
![screen shot 2018-07-19 at 2 05 36 pm](https://user-images.githubusercontent.com/5617217/42961554-0deee2a8-8b5d-11e8-88c0-2de99694c173.png)

**Comment by LTLA** [comment]
Your post disappeared on me, so I'll just put it back here:

> Thanks for the quick response. Yes, it is an irlba issue. I checked the relevant posts, but failed to reach a solution.
> 
> Here the follwing is the command I used:
> sce <- denoisePCA(sce, technical=new.trend, approx=TRUE)
> 
> It is pretty much what is in the Bioconductor workflow (Analyzing single-cell RNA sequencing data from droplet-based protocols).
> 
> Nice catch on the 'nv' value. I was debugging in R and the 'nv' is actually not 5, but 100 (as shown screenshot attached), even though the error message show 5. I assume that is only the default value shown in the function definition.

I guess the simplest solution is to (i) ensure that all values in the matrix `y` are finite, (ii) check that `y` has more than 100 columns/rows, and (iii) confirm that there are no all-zero rows or columns. If these are all fine, I would save `y` to an RDS file (while in debug mode), reload it in a clean R session and confirm that the `irlba` call still fails, and then file a bug report at https://github.com/bwlewis/irlba.

**Comment by luolingqi** [comment]
Thanks  Aaron. I was able to follow your workflow in a clean R session yesterday. I must have messed sth up previously, so I just delete the post because I don’t want more confusion here. I will check in more detail about what you mentioned to see how it meets all them. Thanks

**Comment by LTLA** [comment]
Okay. I'll close this issue for the time being, then.
