### ISSUE TITLE
Installation scran package for R version 3.5.0

### ISSUE THREAD

**Issue by nhuhoa** [MarioniLab/scran#16]
Dear Marioni's group, 

I tried to install package scran and test the function fastMNN using the guide in this page: 
https://rdrr.io/github/MarioniLab/scran/
install.packages("devtools")
library(devtools)
install_github("MarioniLab/scran")

However, I used Rstudio-server and R version 3.5.0. And it failed 
to install this package, the log file is: 
package ‘kmknn’ is not available (for R version 3.5.0)
package ‘scran’ is not available (for R version 3.5.0)

Have you ever tested your package using R version 3.5.x? 
Thanks a lot, 
Best Regards, 
Hoa Tran

**Comment by LTLA** [comment]
You could make life easier for yourself and follow the official instructions:

https://bioconductor.org/packages/devel/bioc/html/scran.html

**Comment by nhuhoa** [comment]
Dear LTLA, 

Thanks a lot for your help. I have successfully installed this package. 

Best, 
Hoa Tran
