### ISSUE TITLE
object ‘areSizeFactorsCentred’ is not exported by 'namespace:scater'

### ISSUE THREAD

**Issue by liuyongcds** [MarioniLab/scran#23]
I have installed all the library successfully and they are also the latest version. However, I have this issue with load scran failed.
> library(DropletUtils)
> library(SingleCellExperiment)
> library(scater)
> library(SC3)
> library(scran)
Error: package or namespace load failed for ‘scran’:
 object ‘areSizeFactorsCentred’ is not exported by 'namespace:scater'
Best,
Yong

**Comment by LTLA** [comment]
Are you sure you've installed the latest version? _scran_ is on 1.10.1, _scater_ is on 1.10.0 for release. Make sure you don't have any problems when you run `BiocManager::valid()`.

**Comment by liuyongcds** [comment]
> Are you sure you've installed the latest version? _scran_ is on 1.10.1, _scater_ is on 1.10.0 for release. Make sure you don't have any problems when you run `BiocManager::valid()`.

Thank you LTLA,
I have check the version of scran. I have reinstalled the scran and fix the issue.
Best,
Yong
