### ISSUE TITLE
References to `normalize`

### ISSUE THREAD

**Issue by robertamezquita** [MarioniLab/scran#26]
Scattered references throughout docs to (defunct?) function `normalize()`, for example in `multiBatchNorm()` function docs

**Comment by LTLA** [comment]
No, that's correct. See `scater::normalize`. Why do you think it is defunct?

**Comment by robertamezquita** [comment]
Sorry, I didn't realize it was a function within scater not scran. Makes sense since scran imports scater but was a bit confused just reading the reference manual since clicking on the links would just take me back to the top of the reference manual. I should've just tried it after loading scran. Sorry!
