### ISSUE TITLE
object ‘normalizeCounts’ is not exported by 'namespace:scater'

### ISSUE THREAD

**Issue by DadongZ** [MarioniLab/scran#27]
Hi I got the below error message when load scran package:
```
No methods found in package ‘DelayedArray’ for request: ‘write_block_to_sink’ when loading ‘DelayedMatrixStats’
Error: package or namespace load failed for ‘scran’:
 object ‘normalizeCounts’ is not exported by 'namespace:scater'
```
Any suggestions?

**Comment by LTLA** [comment]
Make sure you're `BiocManager::valid()`. I suspect you're mixing packages from different versions of Bioconductor. For me, this works fine:

```r
library(scater)
example(normalizeCounts)
``` 

... which indicates that, in fact, `normalizeCounts`**is** being exported by _scater_.

**Comment by LTLA** [comment]
I'm going to assume that this problem was solved, unless told otherwise.
