### ISSUE TITLE
'clusters' or 'cluster' in computeSumFactor

### ISSUE THREAD

**Issue by yicheinchang** [MarioniLab/scran#29]
Hi,

Just a very naive question.
In the reference manual of `scran`, `computeSumFactors` has one argument named `clusters`. However, in almost all of the documents/tutorials, people use `cluster` instead of `clusters`.

For instance:

 - [scran / vignettes](http://bioconductor.org/packages/release/bioc/vignettes/scran/inst/doc/scran.html#4_normalizing_cell-specific_biases)
 - [simpleSingleCell / 04. Droplet-based data ](https://bioconductor.org/packages/release/workflows/vignettes/simpleSingleCell/inst/doc/work-3-tenx.html#6_normalizing_for_cell-specific_biases)

Are `cluster` and `clusters` interchangeable in `computeSumFactors`?

Thanks,
Yi-Chien (Bart).

**Comment by LTLA** [comment]
R will just expand `cluster=` in the function call to `clusters=`. For example:

```r
FUN <- function(someReallyLongArgument) {
    someReallyLongArgument + 1
}

FUN(some=1)
```

**Comment by yicheinchang** [comment]
I see...Thanks :)
