### ISSUE TITLE
Finding C++ code for cxx_smooth_gaussian_kernel

### ISSUE THREAD

**Issue by dylkot** [MarioniLab/scran#33]
Apologies as I am not a regular R user. But I am having a hard time finding the code for cxx_smooth_gaussian_kernel which you use in the compute.correction.vectors function of mnnCorrect.R. It seems that it may be registered in the init.cpp file:

`
./src/init.cpp:57:    REGISTER(smooth_gaussian_kernel, 4),
`
but that still doesn't help me find the actual code. Thanks!

**Comment by LTLA** [comment]
`find_mutual_nns.cpp`.
