### ISSUE TITLE
Streamline DE machinery

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/scran#42]
- Bring `pairwiseWilcox()` and `pairwiseBinom()` under the auspices of `findMarkers()`
- Deprecate `overlapExprs()`, which is basically just `findMarkers()` for `pairwiseWilcox()` anyway.
- Add a way to quickly get the top markers for use in marker detection in _SingleR_.

**Comment by LTLA** [comment]
Don't forget to add a `lfc=` option for `pairwiseWilcox()`; this could probably be co-opted from `tol=`.

**Comment by kevinrue** [comment]
- [x] return unsorted output from `findMarkers`. This should allow you to just do the following for collating results into a single table.

```
markers.pbmc.up <- findMarkers(sce.pbmc, sce.pbmc$cluster, direction="up", log.p=TRUE)
x <- DataFrame(
  row.names = rownames(sce.pbmc),
  lapply(markers.pbmc.up, "[[", i="log.FDR")
  )
```
