### ISSUE TITLE
Negative expression value in the MNN corrected matrix

### ISSUE THREAD

**Issue by yicheinchang** [MarioniLab/scran#5]
Hi,
One naive question regarding the MNN output.
I tried to run `mnnCorrect` to perform a batch normalization on my data sets. All input matrices have been normalized independently by using the `normalise` in the same `scran` package 

    clusters <- quickCluster(sce1)
    sce1 <- computeSumFactors(sce1, clusters = clusters, size = seq(25, 110, 5))
    sce1 <- normalise(sce1, log_exprs_offset = 1, exprs_values = 'counts')
    clusters <- quickCluster(sce2)
    sce2 <- computeSumFactors(sce2, clusters = clusters, size = seq(25, 110, 5))
    sce2 <- normalise(sce2, log_exprs_offset = 1, exprs_values = 'counts')
    ......
    mnn.result <- mnnCorrect(exprs(sce1), exprs(sce2), exprs(sce3), k = 20, cos.norm.in = TRUE, cos.norm.out = FALSE)

The `cos.norm.out` has been set to `FALSE` so the output matrix should be on the log scale, which is the same as to the input matrices. However, I found that a certain amount of genes had negative expression value in the corrected matrix. 

I guess this is normal after scaling. However, if I really want to get rid of those negative log expression value, what is the best practice? `mnnCorrect` did not allow me to supply a log offset. Will it be OK if I just simply add a constant

    mnn.matrix <- do.call(cbind, mnn.result[[1]])
    mnn.matrix <- mnn.matrix - min(mnn.matrix)

All suggestions and recommended are welcomed.

Thanks in advance,
Yi-Chien.

**Comment by LTLA** [comment]
The negative values are a natural consequence of subtracting log-values during the batch correction. As the algorithm currently stands, there's no sensible way to get rid of them - nor should there be any need to. You can still calculate distances between cells for clustering or t-SNE or whatever.

More generally, it would be unwise to interpret the output values as log-counts, see my answer here:

https://support.bioconductor.org/p/106010/#106014

You'll have to give more details on why you need non-negative values. Are you doing NMF? Adding a constant would probably not be harmless, otherwise we could use NMF for everything.

**Comment by yicheinchang** [comment]
Hi @LTLA 

Really appreciate your help 👍 
Currently, I just try to get my feet wet and haven't think about the NMF yet :) The combined (and normalized) matrix probably will be used for the clustering analysis (SIMLR or SC3) and the differential analysis (MAST, for example) first. Some of them prefer a 'count' matrix and the others may need a log-transformed express matrix so I need to have a better understand of MNN's output first.

If I understand correctly, it is better to use the  cosine normalization matrix (set `cos.norm.out=TRUE`) in the downstream analysis. My questions is how should I interpret NMM's output. Can I simply treat it as a 'regular' (not log-transformed)  expression matrix and feed it into other software packages?

And one more question regarding MNN's output. I found that my output matrices (`cos.norm.out=FALSE`) still contain a lot of zero. I suspect those zero are the zero in the original matrices. However, if the batch correction is just a subtraction of the log scale value, I should see more negative values (and only few zero) in the corrected matrices. Do I misunderstand the MNN?

Thanks,
Yi-Chien.

**Comment by LTLA** [comment]
The idea with the MNN output is to use it - in some manner - to compute distances between cells. If this is what the downstream packages are doing, then great, you can use it, e.g., t-SNE, PCA (which is the same as MDS on the distance matrix, IIRC), distance-based clustering. However, if the downstream packages are needing values equivalent to counts or log-counts (e.g., to fit a count-based model, or to handle zeroes), then it would be much more difficult to use the MNN output; I can only tell you that they're log-expression values, I can't guarantee that they're interpretable as log-counts.

I suppose that the MNN output should play nicely with most clustering and trajectory reconstruction methods, e.g., SC3, probably destiny and monocle, as these are based on distances. However, it won't be happy with model-based methods, e.g., MAST or BASiCS. 

As for the zeroes; subtraction is only performed for batches other than the first, as all batches are corrected to the first batch. I guess that you are observing zeroes in the first batch, which has no further manipulation other than a cosine normalization step where zeroes will remain zeroes.

**Comment by yicheinchang** [comment]
Hi @LTLA ,

Thank you soooo much. This is very helpful.

But I still have a few naive questions, especially for the zero in the normalized matrices.

First you are right that I was looking at the zeroes in the first batch. MNN (by nature) will introduce some negative values into the expression matrices.  So in the output matrices the minimum is not 'zero' any more (for sure 0 > any negative values). Will those 'artificial' expression values cause any problems in the downstream analysis?

And things become a little bit tricky in the other batches. I observed that a zero can become a positive value or a negative value after MNN in batches other then the first. Will MNN imply another gene level normalization (row normalization)?

In addition, It seems MNN would not put all matrices on the same baseline after the batch normalization. The normalized matrix from the first batch will still have a lots of zeroes but the others won't (I use zero as a reference point since they represent no read/count in the original matrices). Would you recommend having a second stage normalization before running `cbind`?

By the way, I currently only had a result from setting `cos.norm.out=FALSE`. I will try to generate a cosine normalized output (`cos.norm.out=TRUE`) and see how thing goes.

Thanks again,
Yi-Chien.

**Comment by LTLA** [comment]
The corrected expression values won't cause any problems if you use them for computing distances between cells - that's their intended use. More generally, you can interpret them as measures of expression, in the sense that higher values represent higher expression values. For this, it doesn't matter whether something is zero, positive or negative. 

I don't see why it would be necessary or desirable to perform row-based normalization to fulfil some aesthetic sense about what the data should look like. The fact that some zeroes become non-zero (negative/positive) is a side effect of the batch correction doing its job. If you choose to apply additional transformations on top of that, then you're on your own.

I think the whole zeroes/non-zeroes discussion is a red herring in this context. The real metric of interest here is the distance between cells, and that calculation doesn't change regardless of how many zeroes or non-zeroes you have here. The story might be different if you were using zero-inflated models downstream, but as I said before, this is not advisable for corrected values.

**Comment by lengfei5** [comment]
Hi, 
I am also using the mnnCorrect funciton for our single cell RNA-seq data, which was designed to cover a developmental process with 7 time points. Only adjacent time points have overlapping cell types or population.  
I appreciate if some details can be clarified.

1) the inputs for mnnCorrect are expression matrix in log scale, right ? similar to fastMNN.

2) Since I normalized already the data before the batch correction, may I turn off 
 cos.norm.in = FALSE, cos.norm.out = FALSE ? what is the consequence if doing so ?

3) After the batch correction, I want to cluster my cells. Do I need to identify highly variable genes and do dimensionality reduction (e.g. PCA) using the "corrected expression matrix ", or the output of mnnCorrect ?

4) I understand that the output of mnnCorrect is not logcount anymore and many properties are lost. But the output can still be approxy of gene expression, right ? 
In addtion, in this case, how to do DE analysis or find marker genes for each cluster ? batch by batch is not ideal, right ?

I probably missed comments for some of my questions, but thanks a lot.
Jingkui

**Comment by LTLA** [comment]
1. Yes.
2. Yes, provided that the different batches have roughly the same scale of counts. If one batch has per-cell coverage that is much greater than another batch, consider running `multiBatchNorm()` beforehand.
3. I don't understand your question: the corrected expression matrix _is_ the output of `mnnCorrect()`. You should have been using highly variable genes in `mnnCorrect()` itself, so then you can just use the output directly for PCA or whatever you would like to do.
4. See comments [here](https://bioconductor.org/packages/3.9/workflows/vignettes/simpleSingleCell/inst/doc/batch.html#7_using_the_corrected_values_in_downstream_analyses). I would only use the per-gene corrected values for visualizations accompanying plots generated using the same corrected values - this is mostly to avoid readers being distracted by the differences in expression between batches. For more quantitative analyses, I go back to the original counts, which also serves as a sanity check against errors in correction.

It's worth elaborating on point **4** a bit more. Done properly, the correction will eliminate **all** differences between batches. This includes possibly interesting DE if your batches correspond to different biological conditions. By going back to the original counts, you improve your chances of detecting such DE. For example, if you ran MNN on activated and unactivated T cells, you'd probably get a single giant blob of T cells at the end; but using the original counts for your DE would reveal the activation signature.

**Comment by lengfei5** [comment]
Dear Aaron, 

Thank you so much for your quick anwser, which helps me tremendously. 
So If I understand correctly, the output of mnnCorrect() is indeed the batch-corrected gene expression, but its main usage is for visulization. 
The low-dimension PCA, that is the output from fastMNN(),  will be used to define distance for the clustering or trajectory or whatever downstream analysis. 
DE analysis will be done again with original counts or logcounts, in the similar way to DESeq2 or edgeR. 
So, in my case, different batches cover different cell populations with partial overlap.  
If I run DE with findMarkers() with block=Batches, the markers could be well found, right ?

Thank you sharing the new version of vignette, which contains more information than the one released in 2019-01-09.

**Comment by LTLA** [comment]
>  So If I understand correctly, the output of mnnCorrect() is indeed the batch-corrected gene expression, but its main usage is for visulization.

No. The main usage of the `mnnCorrect()` output is the same as that of the output from `fastMNN()`. It's just that the `mnnCorrect()` output is reported with respect to genes, while `fastMNN()` reports its output with respect to PCs. You can go from one to the other pretty easily:

- Take the `mnnCorrect()` output and run PCA on it to get corrected PCs.
- Take the `fastMNN()` output and multiply it by the rotation vectors (you need to set `get.rotation=TRUE` - I can't remember the exact argument name) to get corrected expression values.

Both of them can be used for clustering or whatever you want to do.

> So, in my case, different batches cover different cell populations with partial overlap. 
If I run DE with findMarkers() with block=Batches, the markers could be well found, right ?

If you use `block=`, the function will only report DE statistics for pairs of populations that co-occur in at least one batch. You won't get DE results between populations that never occur in the same batch. To handle such cases, use `design=` instead, see [here](http://bioconductor.org/packages/devel/workflows/vignettes/simpleSingleCell/inst/doc/de.html#2_blocking_on_uninteresting_factors_of_variation) for details.

**Comment by lengfei5** [comment]
Oh, your anwser comes even faster this time.  I feel you are alway there...

Now I do understand the relationship betwen mnnCorrect() and fastMNN().
Thanks again for guiding me about the DE analysis and I will look into the link.
Great and thanks a lot indeed.

**Comment by lengfei5** [comment]
Dear Aaron, 
I apologize for this again. 

As you explained, the outputs of mnnCorrect() and fastMNN() are just matter of rotation (or linear transformation). 
To confirm this, I run the following code, 
which is mainly aiming to correct my data with three batches. 

I run both fastMNN and mnnCorrect. Then I run PCA for mnnCorrect ouput and compare the first two PCs with the ones from fastMNN. 
Some differences were shown (see attached pdf). 
I spend time testing different parameters for mnnCorrect() and runPCA(), since there are quite some. However, the difference is still there. 
Could you help with this ? It is possible that I run perhaps those functions in a wrong way or I was using some non-optimal parameters.
Or this is something we do expect ? 
Thank you very much for your time.

```
# sce is my object and gene.chosen is my selection of HVGs

# here I have three batches
R6879 = logcounts(sce[ , which(sce$request == "R6875")])  
R7116 = logcounts(sce[ , which(sce$request == "R7116")])  
R7130 = logcounts(sce[ , which(sce$request == "R7130")]) 
original <- list( R6879 = R6879,  R7116 = R7116, R7130 = R7130)

set.seed(100) # run fastMNN
mnn.out <- do.call(fastMNN, c(original, list(k=20, cos.norm = TRUE, d=50, subset.row = gene.chosen, auto.order=c(3,2,1),    approximate=TRUE))) 
reducedDim(sce, "MNN") <- mnn.out$corrected

set.seed(100) # run mnnCorrect
require(BiocParallel)
bpp <- MulticoreParam(5)
mnn.out2 = mnnCorrect(R6879, R7116, R7130, k = 20, sigma = 0.1, cos.norm.in = TRUE, cos.norm.out = TRUE, order = c(3, 2, 1), 
                       svd.dim = 0,
[fastMNN_vs_mnnCorrect.pdf](https://github.com/MarioniLab/scran/files/2803483/fastMNN_vs_mnnCorrect.pdf)
 subset.row = gene.chosen,  pc.approx = TRUE, BPPARAM=bpp)

res1 <- mnn.out2$corrected[[1]] ;
res2 <- mnn.out2$corrected[[2]]
res3 <- mnn.out2$corrected[[3]]
dimnames(res1) <- dimnames(R6879)
dimnames(res2) <- dimnames(R7116)
dimnames(res3) <- dimnames(R7130)
res = cbind(res1, res2, res3)
  
assay(sce, "corrected") <- res

# calculate PCA from output from output of mnnCorrect()
csce <- runPCA(sce, ncomponents = 50, method="irlba", exprs_values = "corrected", feature_set = gene.chosen,  scale_features = TRUE, detect_outliers = FALSE)
  
xx = as.data.frame(reducedDim(csce, "MNN"))
yy = as.data.frame(reducedDim(csce, "PCA"))
  
par(mfrow = c(1, 2))
plot(xx[, c(1:2)], xlab = 'PC1', ylab = "PC2", main = "lowDim output from fastMNN")
plot(yy[, c(1:2)], xlab = 'PC1', ylab = "PC2", main = "PCA from mnnCorret output")
```

[fastMNN_vs_mnnCorrect.pdf](https://github.com/MarioniLab/scran/files/2803486/fastMNN_vs_mnnCorrect.pdf)

**Comment by LTLA** [comment]
My comments above describe how you can get the same _type_ of output, not exactly the same output. It is not possible to get exactly the same values as `fastMNN` and `mnnCorrect` have some fundamental differences, e.g., NNs detected in different spaces. A big difference is that `fastMNN` performs an orthogonalization step to solve the kissing problem. Another difference is that the PCA in `fastMNN` is "balanced" to avoid giving excessive weight to large batches. See [here](https://github.com/MarioniLab/FurtherMNN2018/tree/master/theory) for details of the theory behind `fastMNN`.

**Comment by lengfei5** [comment]
Many thanks for your prompt answer and your great support again.
