### ISSUE TITLE
findMarkers test.type functionality broke

### ISSUE THREAD

**Issue by ONeillMB1** [MarioniLab/scran#50]
I think the test.type functionality of findMarkers() has broke. 

When I try running my former code after updating the package I now get the following error message: Error in .local(x, ...) : unused argument (test.type = "wilcox")

**Comment by LTLA** [comment]
Huh. Are you sure you're using the latest release version? It should be 1.14.5.

**Comment by ONeillMB1** [comment]
Ah, yes, it appears I am loading an older version. Apologies. The break must have come from running it on my desktop (R 3.5) rather than our server (R 3.6). 

Bioconductor version 3.8 (BiocManager 1.30.4), R 3.5.0 (2018-04-23)
Installing package(s) 'scran'
trying URL 'https://bioconductor.org/packages/3.8/bioc/bin/macosx/el-capitan/contrib/3.5/scran_1.10.2.tgz'
Content type 'application/x-gzip' length 3556544 bytes (3.4 MB)
==================================================
downloaded 3.4 MB
