### ISSUE TITLE
is sizeFactorNames being removed now in scran?

### ISSUE THREAD

**Issue by LuyiTian** [MarioniLab/scran#6]
```
sce = computeSumFactors(sce)
sce = normalize(sce)
var.fit = trendVar(sce, method="loess", use.spikes=TRUE)

```

you will have errors:

`Error in sizeFactorNames(object) : could not find function "sizeFactorNames"`

 in `normalize`, add `centre_size_factors = FALSE` avoid the error but you still have the same error when running `trendVar`. I think it is because `trendVar` check the size factors by `.check_centered_SF(x, assay.type=assay.type)`.

**Comment by LTLA** [comment]
IIRC, `sizeFactorNames` was added to the BioC-devel version of _SingleCellExperiment_. So if you only have the BioC-release version of _SingleCellExperiment_ installed, it probably won't work.

**Comment by LuyiTian** [comment]
Ok, think you. I checked scran and scater but havnt think about SCE. I installed the new one because the current release has a bug in MDS that it gives the same result even when you use different expression slot assay. 

BTW. My benchmark dataset shows your scran is the best in normalizations, better than these methods that have complicated model.

**Comment by LTLA** [comment]
Thanks for letting me know, that's reassuring.

**Comment by dhuvik** [comment]
Hi Aaron, I seem to be having the same problem but on the current BioConductor (3.6) It wont update to 3.7 using biocLite() for some reason. However, when trying to use the calcAverage function I get an error saying could not find function sizeFactorNames. [https://support.bioconductor.org/p/109555/](url) and [https://stackoverflow.com/questions/50613564/could-not-find-function-sizefactornames-bioconductor-r3-5](url) for your reference. I have tried reverting back to the non-devel versions of the packages as well with no success

**Comment by LTLA** [comment]
Well, fix your update problem first; read https://bioconductor.org/install/#troubleshoot-bioconductor-packages.

**Comment by dhuvik** [comment]
Thank you! Removing all packages installed through BioConductor and Reinstalling BioConductor seemed to fix everything.
