### ISSUE TITLE
Cyclone usage

### ISSUE THREAD

**Issue by Nusob888** [MarioniLab/scran#60]
Hi, 

I just wanted to check whether cyclone is meant to accept a transformed/scaled gene count matrix or the raw counts? It is unclear from the documentation and there is no direct mention of this in any vignettes. 

Many thanks for your help with this.

**Comment by LTLA** [comment]
Doesn't matter, as long as the transformation is monotonic increasing within each cell. The method is rank-based so you can give it raw counts or log-transformed values, you'll get the same result.

**Comment by Nusob888** [comment]
Great thanks for clarifying @LTLA
