### ISSUE TITLE
Suggestion to `combineVar` function

### ISSUE THREAD

**Issue by AndrMenezes** [MarioniLab/scran#68]
Hello, 

I am using the `combineVar` to averaging the variance components across 11 batches. 
The `DataFrames` objects are in a list.
The `combineVar` function requires to pass the `DataFrames` objects separately by comma and the first line code of the function performed:
`collected <- list(...)`

My suggestion is to include an optional argument to pass the `DataFrames` objects in a list.
This will be helpful when there are several objects.

**Comment by LTLA** [comment]
I can do that, but FYI, you can just do `do.call(combineVar, your_list_of_objects)` for the time being.

**Comment by AndrMenezes** [comment]
Thanks!

**Comment by LTLA** [comment]
I'm going to reopen this, just to remind myself to add a list mode to this function.
