### ISSUE TITLE
"assay.type" in the modelGeneVarByPoisson man page

### ISSUE THREAD

**Issue by ycl6** [MarioniLab/scran#81]
Like `modelGeneVarWithSpikes`, the specified assay should contain counts instead of logcounts.

https://github.com/MarioniLab/scran/blob/424c5ce8f07548b85b0f002b3b51c655aa7957d6/man/modelGeneVarByPoisson.Rd#L69

**Comment by LTLA** [comment]
Well spotted, thanks.
