### ISSUE TITLE
findmarkers summary.logFC values

### ISSUE THREAD

**Issue by cstrlln** [MarioniLab/scran#89]
Hello,
noticed that the summary.logFC is just the smallest value among the reported logFC's when using findMarkers. is this as expected?
Thank you

**Comment by LTLA** [comment]
If you read `?findMarkers`, you will be redirected to `?combineMarkers`, which says (assuming you're using the default `pval.type="any"`):

>     For each gene and cluster, the summary effect size is defined as
>     the effect size from the pairwise comparison with the lowest
>     p-value. The combined p-value is computed by applying Simes'
>     method to all p-values. Neither of these values are directly used
>     for ranking and are only reported for the sake of the user.

If you don't like that definition, you can try some of the other `pval.type=`, or compute your own statistics and supply them to `findMarkers()` via `row.data`. The latter is effectively how `summaryMarkerStats()` works.
