### ISSUE TITLE
Installation is failing

### ISSUE THREAD

**Issue by prvst** [MarioniLab/scran#91]
Hi. I'm running a Linux Mint 20.1 box, with R v4.0.5. I get the following message when trying to install your package.

```
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘.assignIndicesToWorkers’ is not exported by 'namespace:scater'
Execution halted
ERROR: lazy loading failed for package ‘scran’
* removing ‘/R/x86_64-pc-linux-gnu-library/4.0/scran’
```

**Comment by LTLA** [comment]
Are you using `BiocManager::install()`?

**Comment by prvst** [comment]
Yes

**Comment by LTLA** [comment]
Well, you don't really give much more information, so I don't know what you're doing here. **scran** has not depended on **scater** for at least a year now, so I don't see how that error message is even possible. Make sure you're using BioC 3.12 and fix any problems raised by `BiocManager::valid()`.

**Comment by prvst** [comment]
Sorry if that wasn't enough. Please let me know what else would you like to know:

I went to the Bioconductor page: https://bioconductor.org/packages/devel/bioc/html/scran.html

copied the install snippet:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("scran")
```
And tried to run on my terminal (running R): The installation ends with the message I pasted above:

```
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘.assignIndicesToWorkers’ is not exported by 'namespace:scater'
Execution halted
ERROR: lazy loading failed for package ‘scran’
* removing ‘/R/x86_64-pc-linux-gnu-library/4.0/scran’

The downloaded source packages are in
	‘/tmp/RtmpLrKed0/downloaded_packages’
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    mgcv, spatial
Warning message:
In install.packages(...) :
  installation of package ‘scran’ had non-zero exit status
```


EDIT: sorry, I accidentally closed the issue.

**Comment by prvst** [comment]
`

**Comment by LTLA** [comment]
I don't see how this is possible if you're pulling down the most recent version of Bioconductor packages. Run `BiocManager::valid()` and fix any problems that arise.

**Comment by prvst** [comment]
Got it. Had to update BiocManager and all packages. Thanks.
